spring.application.name=crud
spring.datasource.url=jdbc:mysql://localhost:3306/crud?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8085

#Enabling multipart
spring.servlet.multipart.enabled=true

#max file size
spring.servlet.multipart.max-file-size=300MB

#Threshold after which files are written to disk
#spring.servlet.multipart.file-size-threshold=1kb

