name: hello-world  

on:   
  push:   
    branches:   
      - sonali_crud  # Specify the branch to which this action applies  

jobs:  
  my-job:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  # Ensure the code is checked out  

      - name: Run my step  
        run: echo "Hello World!"
